app = "connexio-file-bot"
primary_region = "iad"

[build]
  dockerfile = "production.Dockerfile"

[env]
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[http_service.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[processes]
  app = "node enhanced-file-bot.js"