# Fly.io configuration for Postgres Database
app = "connexio-ai-postgres"
primary_region = "iad"

[build]
  image = "postgres:16-alpine"

[env]
  # Postgres configuration
  POSTGRES_DB = "connexio_ai"
  POSTGRES_USER = "connexio_ai_user"
  PGDATA = "/var/lib/postgresql/data"
  
  # Performance tuning
  POSTGRES_SHARED_BUFFERS = "1GB"
  POSTGRES_EFFECTIVE_CACHE_SIZE = "3GB"
  POSTGRES_MAINTENANCE_WORK_MEM = "256MB"
  POSTGRES_CHECKPOINT_COMPLETION_TARGET = "0.9"
  POSTGRES_WAL_BUFFERS = "16MB"
  POSTGRES_DEFAULT_STATISTICS_TARGET = "100"
  POSTGRES_RANDOM_PAGE_COST = "1.1"
  POSTGRES_EFFECTIVE_IO_CONCURRENCY = "200"
  POSTGRES_WORK_MEM = "4MB"
  POSTGRES_MIN_WAL_SIZE = "1GB"
  POSTGRES_MAX_WAL_SIZE = "4GB"
  
  # Connection settings
  POSTGRES_MAX_CONNECTIONS = "200"
  POSTGRES_SHARED_PRELOAD_LIBRARIES = "pg_stat_statements"
  
  # Logging
  POSTGRES_LOG_STATEMENT = "all"
  POSTGRES_LOG_MIN_DURATION_STATEMENT = "1000"

[vm]
  cpu_kind = "performance"
  cpus = 4
  memory = "8gb"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    port = 5432

  [[services.concurrency]]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[mounts]]
  source = "postgres_data"
  destination = "/var/lib/postgresql/data"
  snapshot_retention = 30

# Backup configuration
[[statics]]
  guest_path = "/app/backups"
  url_prefix = "/backups"

[processes]
  postgres = """
    postgres \
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS} \
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE} \
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM} \
      -c checkpoint_completion_target=${POSTGRES_CHECKPOINT_COMPLETION_TARGET} \
      -c wal_buffers=${POSTGRES_WAL_BUFFERS} \
      -c default_statistics_target=${POSTGRES_DEFAULT_STATISTICS_TARGET} \
      -c random_page_cost=${POSTGRES_RANDOM_PAGE_COST} \
      -c effective_io_concurrency=${POSTGRES_EFFECTIVE_IO_CONCURRENCY} \
      -c work_mem=${POSTGRES_WORK_MEM} \
      -c min_wal_size=${POSTGRES_MIN_WAL_SIZE} \
      -c max_wal_size=${POSTGRES_MAX_WAL_SIZE} \
      -c max_connections=${POSTGRES_MAX_CONNECTIONS} \
      -c shared_preload_libraries=${POSTGRES_SHARED_PRELOAD_LIBRARIES} \
      -c log_statement=${POSTGRES_LOG_STATEMENT} \
      -c log_min_duration_statement=${POSTGRES_LOG_MIN_DURATION_STATEMENT}
  """

[metrics]
  port = 9187
  path = "/metrics"

[deploy]
  strategy = "immediate"
  release_command = "/app/scripts/init-db.sh"