# Simple Fly.io configuration for Slack Bot
app = "connexio-slack-simple"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[http_service.http_check]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"
    port = 3000

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

[processes]
  app = "node src/claude-enhanced-bot.js"

[deploy]
  strategy = "immediate"