# Fly.io configuration for Little Horse Task Workers
app = "connexio-ai-workers"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  # Node.js configuration
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  
  # Little Horse connection
  LITTLEHORSE_API_HOST = "connexio-ai-littlehorse.internal"
  LITTLEHORSE_API_PORT = "2023"
  
  # Worker configuration
  MAX_CONCURRENT_TASKS = "10"
  HEARTBEAT_INTERVAL_MS = "5000"
  TASK_TIMEOUT_MS = "300000"
  
  # Rate limiting
  RATE_LIMIT_MAX_CONCURRENT = "5"
  RATE_LIMIT_INTERVAL_CAP = "100"
  RATE_LIMIT_INTERVAL = "60000"
  
  # Data enrichment defaults
  DATA_ENRICHMENT_DEFAULT_STRATEGY = "comprehensive"
  DATA_ENRICHMENT_MAX_CONCURRENT = "5"
  DATA_ENRICHMENT_ENABLE_CREDIT_MONITORING = "true"
  
  # Real-time sync defaults
  REALTIME_SYNC_INTERVAL = "300000"
  REALTIME_SYNC_BATCH_SIZE = "100"
  REALTIME_SYNC_ENABLE_CHANGE_DETECTION = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[http_service.http_check]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"
    port = 3000

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory = "2gb"

[processes]
  app = "npm start"


[deploy]
  strategy = "canary"


# Auto-scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 10

[[scaling.metrics]]
  type = "cpu"
  target = 70

[[scaling.metrics]]
  type = "memory" 
  target = 80

[[scaling.metrics]]
  type = "requests_per_second"
  target = 100